### ISSUE TITLE
ANLI model

### ISSUE THREAD

**Issue by UntotaufUrlaub** [google-research/true#14]
Hi,

I would like to reuse/reevaluate your ANLI and Q2-relaxed metric, have you shared code and model? I did not see it in this repo.

kind regards

**Comment by roeeaharoni** [comment]
Hi, the NLI model we open-sourced is available here: https://huggingface.co/google/t5_xxl_true_nli_mixture
Re Q^2, the open-sourced version is available here: https://github.com/orhonovich/q-squared (it is of lower quality than the one used in the paper).
