### ISSUE TITLE
404 Error when downloading BEGIN benchmark

### ISSUE THREAD

**Issue by nightdessert** [google-research/true#4]
Hi, I encountered 404 Error when downloading BEGIN benchmark.
Maybe update the address, or proving the script to preprocess the open-sourced version BEGIN on github.
Thanks a lot.

**Comment by perlitz** [comment]
you can find the files you are looking for here: https://github.com/google/BEGIN-dataset/tree/6f881995bca5405918f3138b04f29fdd2a1b73ae

Just download them and read them from file.

**Comment by roeeaharoni** [comment]
Thanks both! Submitted a fix, closing.
