### ISSUE TITLE
ModuleNotFoundError: No module named 'google3'

### ISSUE THREAD

**Issue by Yujin-Yujin** [google-research/true#5]
To run the meta_evaluation_scores.py, I installed the requirement.txt.
However, there is below error.
Please let me know how to solve or install.

`Traceback (most recent call last):
  File "src/meta_evaluation_scores.py", line 29, in <module>
    from google3.third_party.google_research.google_research.true import meta_evaluation_lib
ModuleNotFoundError: No module named 'google3`

**Comment by Yujin-Yujin** [comment]
Oh I found that just simple path error.

**Comment by ds704** [comment]
Hi,
i get the same error. Can you please explain how you solved it?

**Comment by thangld201** [comment]
Hi @roeeaharoni , can you help ? I also get this error.
